<InvoiceData xmlns="http://schemas.nav.gov.hu/OSA/3.0/data" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.nav.gov.hu/OSA/3.0/data invoiceData.xsd" xmlns:common="http://schemas.nav.gov.hu/NTCA/1.0/common" xmlns:base="http://schemas.nav.gov.hu/OSA/3.0/base" >
 <invoiceNumber>ASZ2300056</invoiceNumber>
 <invoiceIssueDate>2023-01-12</invoiceIssueDate>
 <completenessIndicator>false</completenessIndicator>
 <invoiceMain>
  <invoice>
   <invoiceHead>
    <supplierInfo>
     <supplierTaxNumber>
      <base:taxpayerId>27856873</base:taxpayerId>
      <base:vatCode>2</base:vatCode>
      <base:countyCode>41</base:countyCode>
     </supplierTaxNumber>
     <supplierName>Alapkő Szövetkezet</supplierName>
     <supplierAddress>
      <base:detailedAddress>
       <base:countryCode>HU</base:countryCode>
       <base:postalCode>1134</base:postalCode>
       <base:city>Budapest</base:city>
       <base:streetName>Váci</base:streetName>
       <base:publicPlaceCategory>út</base:publicPlaceCategory>
       <base:number>47/B Ü1</base:number>
       <base:floor>.</base:floor>
       <base:door>.</base:door>
      </base:detailedAddress>
     </supplierAddress>
     <supplierBankAccountNumber>10403466-50527067-83711006</supplierBankAccountNumber>
    </supplierInfo>
    <customerInfo>
     <customerVatStatus>DOMESTIC</customerVatStatus>
     <customerVatData>
      <customerTaxNumber>
       <base:taxpayerId>10660258</base:taxpayerId>
       <base:vatCode>2</base:vatCode>
       <base:countyCode>03</base:countyCode>
      </customerTaxNumber>
     </customerVatData>
     <customerName>Szent Imre Pincészet Kft.</customerName>
     <customerAddress>
      <base:detailedAddress>
       <base:countryCode>HU</base:countryCode>
       <base:postalCode>6223</base:postalCode>
  	   <base:city>Soltszentimre</base:city>
  	   <base:streetName>Dózsa György utca 79.</base:streetName>
       <base:publicPlaceCategory>utca</base:publicPlaceCategory>
       <base:number>79.</base:number>
      </base:detailedAddress>
     </customerAddress>
    </customerInfo>
    <invoiceDetail>
     <invoiceCategory>NORMAL</invoiceCategory>
     <invoiceDeliveryDate>2023-01-12</invoiceDeliveryDate>
     <currencyCode>HUF</currencyCode>
     <exchangeRate>1</exchangeRate>
     <paymentMethod>TRANSFER</paymentMethod>
     <paymentDate>2023-01-21</paymentDate>
     <invoiceAppearance>PAPER</invoiceAppearance>
     <additionalInvoiceData>
      <dataName>M00001_MEGJ</dataName>
      <dataDescription>Megjegyzes</dataDescription>
      <dataValue>Köszönjük a vásárlást.</dataValue>
     </additionalInvoiceData>
    </invoiceDetail>
   </invoiceHead>
   <invoiceLines>
    <mergedItemIndicator>false</mergedItemIndicator>
    <line>
     <lineNumber>1</lineNumber>
     <lineExpressionIndicator>true</lineExpressionIndicator>
     <lineNatureIndicator>PRODUCT</lineNatureIndicator>
     <lineDescription>Program támogatás</lineDescription>
     <quantity>3</quantity>
     <unitOfMeasure>OWN</unitOfMeasure>
     <unitPrice>2500.00</unitPrice>
     <lineAmountsNormal>
      <lineNetAmountData>
       <lineNetAmount>7500</lineNetAmount>
       <lineNetAmountHUF>7500</lineNetAmountHUF>
      </lineNetAmountData>
      <lineVatRate>
        <vatPercentage>0.27</vatPercentage>
      </lineVatRate>
      <lineVatData>
       <lineVatAmount>2025</lineVatAmount>
       <lineVatAmountHUF>2025</lineVatAmountHUF>
      </lineVatData>
      <lineGrossAmountData>
       <lineGrossAmountNormal>9525</lineGrossAmountNormal>
       <lineGrossAmountNormalHUF>9525</lineGrossAmountNormalHUF>
      </lineGrossAmountData>
     </lineAmountsNormal>
    </line>
    <line>
     <lineNumber>2</lineNumber>
     <lineExpressionIndicator>true</lineExpressionIndicator>
     <lineNatureIndicator>PRODUCT</lineNatureIndicator>
     <lineDescription>Program támogatás</lineDescription>
     <quantity>91</quantity>
     <unitOfMeasure>MINUTE</unitOfMeasure>
     <unitPrice>425.00</unitPrice>
     <lineAmountsNormal>
      <lineNetAmountData>
       <lineNetAmount>38675</lineNetAmount>
       <lineNetAmountHUF>38675</lineNetAmountHUF>
      </lineNetAmountData>
      <lineVatRate>
        <vatPercentage>0.27</vatPercentage>
      </lineVatRate>
      <lineVatData>
       <lineVatAmount>10442</lineVatAmount>
       <lineVatAmountHUF>10442</lineVatAmountHUF>
      </lineVatData>
      <lineGrossAmountData>
       <lineGrossAmountNormal>49117</lineGrossAmountNormal>
       <lineGrossAmountNormalHUF>49117</lineGrossAmountNormalHUF>
      </lineGrossAmountData>
     </lineAmountsNormal>
    </line>
   </invoiceLines>
   <invoiceSummary>
    <summaryNormal>
     <summaryByVatRate>
      <vatRate>
       <vatPercentage>0.27</vatPercentage>
      </vatRate>
      <vatRateNetData>
       <vatRateNetAmount>46175</vatRateNetAmount>
       <vatRateNetAmountHUF>46175</vatRateNetAmountHUF>
      </vatRateNetData>
      <vatRateVatData>
       <vatRateVatAmount>12467</vatRateVatAmount>
       <vatRateVatAmountHUF>12467</vatRateVatAmountHUF>
      </vatRateVatData>
      <vatRateGrossData>
       <vatRateGrossAmount>58642</vatRateGrossAmount>
       <vatRateGrossAmountHUF>58642</vatRateGrossAmountHUF>
      </vatRateGrossData>
     </summaryByVatRate>
     <invoiceNetAmount>46175</invoiceNetAmount>
     <invoiceNetAmountHUF>46175</invoiceNetAmountHUF>
     <invoiceVatAmount>12467</invoiceVatAmount>
     <invoiceVatAmountHUF>12467</invoiceVatAmountHUF>
    </summaryNormal>
    <summaryGrossData>
     <invoiceGrossAmount>58642</invoiceGrossAmount>
     <invoiceGrossAmountHUF>58642</invoiceGrossAmountHUF>
    </summaryGrossData>
   </invoiceSummary>
  </invoice>
 </invoiceMain>
</InvoiceData>
